# Generated by Django 3.2.10 on 2022-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_username_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
