# Generated by Django 3.2.10 on 2022-01-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.usergroup'),
        ),
    ]
