# Generated by Django 3.2.10 on 2022-01-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_userinfo_ug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
