# Generated by Django 3.2.10 on 2022-01-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20220105_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
