# Generated by Django 3.2.10 on 2022-01-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_usergroup_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=9)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_age', models.IntegerField(null=True)),
                ('cla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.classinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
